export interface Preferences {
  id: string; // This will be the userId for easy lookup
  userId: string;
  focusSessionLength: string;
  breakLength: string;
  focusBreakers: string[];
  preferredOutput: string;
  detailLevel: string;
  colorTheme: string;
  audioSpeed: string;
  videoSpeed: string;
  sessionStyle: string;
  progressTracking: string;
  energyLevel: string;
  scrollSpeed: string;
  
  // Fields generated by Azure OpenAI
  aiEvaluation: {
    adhdLevel: number; // 1-5 scale
    focusIntensity: string;
    sensoryNeeds: string[];
    recommendedPomodoro: number;
    personalizedInsight: string;
  };
  
  lastEdit: string;
}